### ISSUE TITLE
please create a tag

### ISSUE THREAD

**Issue by SabineMa** [hernanmd/FixedDecimal#1]
I am moving my baseline from Smalltalkhub to GitHub. I used this for loading

```
spec
		project: 'OrderPreservingDictionary'
		with: [ spec
				className: #ConfigurationOfOrderPreservingDictionary;
				version: '1.4.0';
				loads: #('default');
				repository: 'http://smalltalkhub.com/mc/PharoExtras/OrderPreservingDictionary/main' ]
```

now, I will use this
```
spec 
	baseline: 'FixedDecimal'
	with: [ spec repository: 'github://hernanmd/FixedDecimal:xxx/repository' ]
```

I would like to have a tag or a version because I don't want to load code which could change over time

So, I ask for creating a tag. I did not find a way to do it by myself I assume I don't have permission.

**Comment by hernanmd** [comment]
Tagged as v1.0

https://github.com/hernanmd/FixedDecimal/tree/v1.0
